# Generated by Django 5.0.6 on 2024-07-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomk', '0006_alter_rooms_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
