# Generated by Django 5.0.6 on 2024-07-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomk', '0007_alter_rooms_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='payprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(),
        ),
    ]
