# Generated by Django 5.0.6 on 2024-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomk', '0008_rooms_payprice_alter_rooms_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
