# Generated by Django 5.0.6 on 2024-07-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomk', '0009_alter_rooms_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
